name: My First Action To Build,Push,Deploy

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t lfortest/my-firstapp:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push lfortest/my-firstapp:latest
      - name: Auth to Goole Cloud
        uses: google-github-actions/auth@v1
        with: 
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with: 
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Who am I
        run: gcloud auth list
        
      - name: Deploy to GCP
        run: |
          gcloud run deploy my-nb \
            --image=docker.io/lfortest/my-firstapp:latest \
            --platform=managed \
            --region=asia-northeast1 \
            --allow-unauthenticated
            
